config/routes.rb
Rails.application.routes.draw do
  get 'commodities/capture'

  get 'home' => 'pages#home'
  root 'pages#home'
end

app/models/yahoo/finance_api.rb
module Yahoo
  class FinanceAPI

    def initialize(*args)
      @api_url = 'https://query.yahooapis.com/v1/public/yql'
      @query = 'select * from yahoo.finance.quotes where symbol in ("YHOO","AAPL","GOOG","MSFT","CCH16.NYB")'
      @env = 'store://datatables.org/alltableswithkeys'
    end

    def get_commodities
      query = {q: @query,
               format: 'json',
               diagnostics: false,
               env: @env
      }
      response = HTTParty.get(@api_url, query: query)

      if response.code == 200
        commodities = []
        json = JSON.parse(response.body)

        json['query']['results']['quote'].each do |quote|
          begin
            if quote['Name']
              commodity = {symbol: quote['symbol'],
                           name: quote['Name'],
                           change: quote['Change'].sub('%','').to_f,
                           last_trade_price: quote['LastTradePriceOnly'].to_f,
              }
              $redis.set(quote['symbol'], commodity.to_json)
              commodities << commodity
            else
              {error: 'Yahoo API data returned is not well formated.'}
            end
          rescue
            {error: 'Yahoo API data returned is not well formated.'}
          end
        end

        commodities
      else
        {error: 'an error occurred while using Yahoo API.'}
      end
    end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commodities_controller.rb
class CommoditiesController < ApplicationController
  include ActionController::Live

  def capture
    response.headers['Content-Type'] = 'text/event-stream'
    time_in_minutes = params[:time_in_minutes] || 10
    sse = SSE.new(response.stream)
    begin
      loop do
        commodities = Yahoo::FinanceAPI.new.get_commodities.to_json
        sse.write(commodities)
        sleep (time_in_minutes.to_i * 60)
      end
    rescue IOError
      # Client Disconnected
    ensure
      sse.close
    end

    render nothing: true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    companies = ["YHOO","AAPL","GOOG","MSFT","CCH16.NYB"]
    @commodities = []
    companies.each do |company|
      commodity = $redis.get(company)
      if commodity
        @commodities << JSON::parse(commodity).merge(id: company)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinancialCapture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Financial Capture</h1>

<h3>Last commodities</h3>
<table class="table table-striped" id="last-commodities" style="<%= (@commodities.size == 0) ? 'display: none' : '' %>">
  <thead>
  <tr>
    <th>Symbol</th>
    <th>Name</th>
    <th>Last Trade</th>
    <th>Change</th>
  </tr>
  </thead>
  <tbody>
  <% @commodities.each do |commodity| %>
      <tr id="commodity-<%= commodity['symbol'].gsub('.','-') %>">
        <td><%= commodity['symbol'] %></td>
        <td><%= commodity['name'] %></td>
        <td><%= commodity['last_trade_price'] %></td>
        <td><%= commodity['change'] %> %</td>
      </tr>
  <% end %>
  </tbody>
</table>
<% if @commodities.size == 0 %>
    <p id="commodities-empty">Commodities empty, please run to capture</p>
<% end %>

<hr />

<p>Click the button below to start/stop capture commodities</p>

<%= form_tag commodities_capture_path, :method => 'get', :id => 'run', class: 'form-inline' do %>
    <div class="form-group">
      <%= text_field_tag :time_in_minutes, params[:time_in_minutes], type: :number, class: 'form-control', placeholder: 'Time interval (minutes)' %>
    </div>
    <%= submit_tag "Run now", :class => 'btn btn-primary' %>
<% end %>

<button id="stop" class="btn btn-danger" style="display: none">Stop</button>

<h3 id="capture-logs-title" style="display: none">Capture logs</h3>
<div id="capture-logs" style="display: none">
</div>